include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/shared/ml/ml_pipeline.g.dart"
    - "lib/shared/database/app_database.g.dart"
  errors:
    invalid_annotation_target: ignore
  plugins:
    - custom_lint

linter:
  rules:
    public_member_api_docs: false
