// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum PipelineStage: Int {
  case initialising = 0
  case extractingFrames = 1
  case detectingBall = 2
  case detectingPoses = 3
  case trackingPlayers = 4
  case segmentingRallies = 5
  case attributingTouches = 6
  case finalising = 7
}

enum PlayerSlot: Int {
  case homeLeft = 0
  case homeRight = 1
  case awayLeft = 2
  case awayRight = 3
}

enum PipelineEventType: Int {
  case progress = 0
  case completion = 1
  case cancelled = 2
  case error = 3
}

/// Tunable parameters for one end-to-end pipeline run.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PipelineConfig {
  var frameRateHz: Int64
  var rallyGapThresholdSeconds: Double
  var minRallyDurationSeconds: Double
  var touchProximityPx: Double
  var detectionConfidenceThreshold: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PipelineConfig? {
    let frameRateHz = pigeonVar_list[0] as! Int64
    let rallyGapThresholdSeconds = pigeonVar_list[1] as! Double
    let minRallyDurationSeconds = pigeonVar_list[2] as! Double
    let touchProximityPx = pigeonVar_list[3] as! Double
    let detectionConfidenceThreshold = pigeonVar_list[4] as! Double

    return PipelineConfig(
      frameRateHz: frameRateHz,
      rallyGapThresholdSeconds: rallyGapThresholdSeconds,
      minRallyDurationSeconds: minRallyDurationSeconds,
      touchProximityPx: touchProximityPx,
      detectionConfidenceThreshold: detectionConfidenceThreshold
    )
  }
  func toList() -> [Any?] {
    return [
      frameRateHz,
      rallyGapThresholdSeconds,
      minRallyDurationSeconds,
      touchProximityPx,
      detectionConfidenceThreshold,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PipelineProgress {
  var stage: PipelineStage
  /// 0.0 .. 1.0 across the whole pipeline (not per-stage).
  var fractionComplete: Double
  var framesProcessed: Int64
  var totalFrames: Int64
  /// Running count of frames in which the ball was detected with
  /// confidence above the configured threshold. Zero when the
  /// detection model is unavailable.
  var ballDetectionsSoFar: Int64
  /// Absolute path to a debug preview thumbnail (typically the first frame).
  /// Populated once, early in the run.
  var previewThumbnailPath: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PipelineProgress? {
    let stage = pigeonVar_list[0] as! PipelineStage
    let fractionComplete = pigeonVar_list[1] as! Double
    let framesProcessed = pigeonVar_list[2] as! Int64
    let totalFrames = pigeonVar_list[3] as! Int64
    let ballDetectionsSoFar = pigeonVar_list[4] as! Int64
    let previewThumbnailPath: String? = nilOrValue(pigeonVar_list[5])

    return PipelineProgress(
      stage: stage,
      fractionComplete: fractionComplete,
      framesProcessed: framesProcessed,
      totalFrames: totalFrames,
      ballDetectionsSoFar: ballDetectionsSoFar,
      previewThumbnailPath: previewThumbnailPath
    )
  }
  func toList() -> [Any?] {
    return [
      stage,
      fractionComplete,
      framesProcessed,
      totalFrames,
      ballDetectionsSoFar,
      previewThumbnailPath,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BallObservation {
  var frameIndex: Int64
  var timestampMs: Int64
  var x: Double
  var y: Double
  var width: Double
  var height: Double
  var confidence: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BallObservation? {
    let frameIndex = pigeonVar_list[0] as! Int64
    let timestampMs = pigeonVar_list[1] as! Int64
    let x = pigeonVar_list[2] as! Double
    let y = pigeonVar_list[3] as! Double
    let width = pigeonVar_list[4] as! Double
    let height = pigeonVar_list[5] as! Double
    let confidence = pigeonVar_list[6] as! Double

    return BallObservation(
      frameIndex: frameIndex,
      timestampMs: timestampMs,
      x: x,
      y: y,
      width: width,
      height: height,
      confidence: confidence
    )
  }
  func toList() -> [Any?] {
    return [
      frameIndex,
      timestampMs,
      x,
      y,
      width,
      height,
      confidence,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TouchEvent {
  var timestampMs: Int64
  var playerSlot: PlayerSlot
  var ballX: Double
  var ballY: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TouchEvent? {
    let timestampMs = pigeonVar_list[0] as! Int64
    let playerSlot = pigeonVar_list[1] as! PlayerSlot
    let ballX = pigeonVar_list[2] as! Double
    let ballY = pigeonVar_list[3] as! Double

    return TouchEvent(
      timestampMs: timestampMs,
      playerSlot: playerSlot,
      ballX: ballX,
      ballY: ballY
    )
  }
  func toList() -> [Any?] {
    return [
      timestampMs,
      playerSlot,
      ballX,
      ballY,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RallyResult {
  var rallyIndex: Int64
  var startTimestampMs: Int64
  var endTimestampMs: Int64
  /// Indexed by PlayerSlot.index. Length is always 4.
  var touchCountBySlot: [Int64]
  var touches: [TouchEvent]
  var ballObservations: [BallObservation]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RallyResult? {
    let rallyIndex = pigeonVar_list[0] as! Int64
    let startTimestampMs = pigeonVar_list[1] as! Int64
    let endTimestampMs = pigeonVar_list[2] as! Int64
    let touchCountBySlot = pigeonVar_list[3] as! [Int64]
    let touches = pigeonVar_list[4] as! [TouchEvent]
    let ballObservations = pigeonVar_list[5] as! [BallObservation]

    return RallyResult(
      rallyIndex: rallyIndex,
      startTimestampMs: startTimestampMs,
      endTimestampMs: endTimestampMs,
      touchCountBySlot: touchCountBySlot,
      touches: touches,
      ballObservations: ballObservations
    )
  }
  func toList() -> [Any?] {
    return [
      rallyIndex,
      startTimestampMs,
      endTimestampMs,
      touchCountBySlot,
      touches,
      ballObservations,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PipelineResult {
  var matchId: String
  var rallies: [RallyResult]
  /// All ball detections from the run, in chronological order. Once rally
  /// segmentation lands these will move into [RallyResult.ballObservations]
  /// and this list will likely disappear; for now they're shipped flat so
  /// the review screen can render an overlay without rallies existing yet.
  var ballObservations: [BallObservation]
  /// Source-video resolution. The review-screen overlay needs this to map
  /// ball bounding boxes (which are in source-pixel coords) into Flutter
  /// layout coordinates.
  var frameWidth: Int64
  var frameHeight: Int64
  var totalFramesProcessed: Int64
  /// Total frames in which the ball was detected with confidence above
  /// the configured threshold. Independent of rally segmentation.
  var totalBallDetections: Int64
  var totalDurationMs: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PipelineResult? {
    let matchId = pigeonVar_list[0] as! String
    let rallies = pigeonVar_list[1] as! [RallyResult]
    let ballObservations = pigeonVar_list[2] as! [BallObservation]
    let frameWidth = pigeonVar_list[3] as! Int64
    let frameHeight = pigeonVar_list[4] as! Int64
    let totalFramesProcessed = pigeonVar_list[5] as! Int64
    let totalBallDetections = pigeonVar_list[6] as! Int64
    let totalDurationMs = pigeonVar_list[7] as! Int64

    return PipelineResult(
      matchId: matchId,
      rallies: rallies,
      ballObservations: ballObservations,
      frameWidth: frameWidth,
      frameHeight: frameHeight,
      totalFramesProcessed: totalFramesProcessed,
      totalBallDetections: totalBallDetections,
      totalDurationMs: totalDurationMs
    )
  }
  func toList() -> [Any?] {
    return [
      matchId,
      rallies,
      ballObservations,
      frameWidth,
      frameHeight,
      totalFramesProcessed,
      totalBallDetections,
      totalDurationMs,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PipelineError {
  var code: String
  var message: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PipelineError? {
    let code = pigeonVar_list[0] as! String
    let message = pigeonVar_list[1] as! String

    return PipelineError(
      code: code,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      message,
    ]
  }
}

/// Single event type carried over the @FlutterApi channel.
/// Exactly one of [progress], [result], or [error] is populated.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PipelineEvent {
  var sessionId: String
  var type: PipelineEventType
  var progress: PipelineProgress? = nil
  var result: PipelineResult? = nil
  var error: PipelineError? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PipelineEvent? {
    let sessionId = pigeonVar_list[0] as! String
    let type = pigeonVar_list[1] as! PipelineEventType
    let progress: PipelineProgress? = nilOrValue(pigeonVar_list[2])
    let result: PipelineResult? = nilOrValue(pigeonVar_list[3])
    let error: PipelineError? = nilOrValue(pigeonVar_list[4])

    return PipelineEvent(
      sessionId: sessionId,
      type: type,
      progress: progress,
      result: result,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      sessionId,
      type,
      progress,
      result,
      error,
    ]
  }
}

private class MLPipelinePigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PipelineStage(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlayerSlot(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PipelineEventType(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return PipelineConfig.fromList(self.readValue() as! [Any?])
    case 133:
      return PipelineProgress.fromList(self.readValue() as! [Any?])
    case 134:
      return BallObservation.fromList(self.readValue() as! [Any?])
    case 135:
      return TouchEvent.fromList(self.readValue() as! [Any?])
    case 136:
      return RallyResult.fromList(self.readValue() as! [Any?])
    case 137:
      return PipelineResult.fromList(self.readValue() as! [Any?])
    case 138:
      return PipelineError.fromList(self.readValue() as! [Any?])
    case 139:
      return PipelineEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MLPipelinePigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PipelineStage {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlayerSlot {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? PipelineEventType {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? PipelineConfig {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? PipelineProgress {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? BallObservation {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? TouchEvent {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? RallyResult {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? PipelineResult {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? PipelineError {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? PipelineEvent {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MLPipelinePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MLPipelinePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MLPipelinePigeonCodecWriter(data: data)
  }
}

class MLPipelinePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MLPipelinePigeonCodec(readerWriter: MLPipelinePigeonCodecReaderWriter())
}


/// Dart -> Swift control surface.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MLPipelineHostApi {
  /// Starts processing the video at [videoPath]. [sessionId] is generated by
  /// Dart so the Dart side can subscribe to events for the session before
  /// the call returns, avoiding a startup race.
  func startProcessing(sessionId: String, matchId: String, videoPath: String, config: PipelineConfig, completion: @escaping (Result<Void, Error>) -> Void)
  /// Cancels an in-flight session. Idempotent.
  func cancel(sessionId: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MLPipelineHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MLPipelinePigeonCodec.shared }
  /// Sets up an instance of `MLPipelineHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MLPipelineHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Starts processing the video at [videoPath]. [sessionId] is generated by
    /// Dart so the Dart side can subscribe to events for the session before
    /// the call returns, avoiding a startup race.
    let startProcessingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ai_beach_stats.MLPipelineHostApi.startProcessing\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startProcessingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        let matchIdArg = args[1] as! String
        let videoPathArg = args[2] as! String
        let configArg = args[3] as! PipelineConfig
        api.startProcessing(sessionId: sessionIdArg, matchId: matchIdArg, videoPath: videoPathArg, config: configArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startProcessingChannel.setMessageHandler(nil)
    }
    /// Cancels an in-flight session. Idempotent.
    let cancelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ai_beach_stats.MLPipelineHostApi.cancel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        do {
          try api.cancel(sessionId: sessionIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelChannel.setMessageHandler(nil)
    }
  }
}
/// Swift -> Dart events. Implemented by the Dart facade and invoked by the
/// native pipeline coordinator as each event occurs.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol MLPipelineEventListenerProtocol {
  func onPipelineEvent(event eventArg: PipelineEvent, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class MLPipelineEventListener: MLPipelineEventListenerProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MLPipelinePigeonCodec {
    return MLPipelinePigeonCodec.shared
  }
  func onPipelineEvent(event eventArg: PipelineEvent, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.ai_beach_stats.MLPipelineEventListener.onPipelineEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
